=== jul-louis/Web-Development-Vol.1/part1/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://localhost" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resume" type="loc:resumeType" xmlns:loc="http://localhost">
        <xs:annotation>
            <xs:documentation>By Louis Kano</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element type="xs:string" name="firstname"/>
            <xs:element type="xs:string" name="lastname"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="street" minOccurs="0"/>
            <xs:element name="city">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Edmonton"/>
                        <xs:enumeration value="Chengdu"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="province">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Alberta"/>
                        <xs:enumeration value="Sichuan"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="postal" minOccurs="0"/>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Canada"/>
                        <xs:enumeration value="China"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="contactType">
        <xs:sequence>
            <xs:element type="xs:string" name="mobile"/>
            <xs:element type="xs:string" name="email"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="informationType">
        <xs:sequence>
            <xs:element type="loc:nameType" name="name" xmlns:loc="http://localhost"/>
            <xs:element type="loc:addressType" name="address" xmlns:loc="http://localhost"/>
            <xs:element type="loc:contactType" name="contact" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="degreeType">
        <xs:sequence>
            <xs:element type="xs:string" name="degree_type"/>
            <xs:element type="xs:string" name="major"/>
            <xs:element type="xs:string" name="faculty"/>
            <xs:element type="xs:string" name="department"/>
            <xs:element type="xs:string" name="career"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="engineering_graduation_averageType">
        <xs:sequence>
            <xs:element type="xs:string" name="grade_point_average"/>
            <xs:element type="xs:string" name="max_possible_value"/>
            <xs:element type="xs:string" name="status"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fromType">
        <xs:sequence>
            <xs:element name="month">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="September"/>
                        <xs:enumeration value="June"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="year"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="toType">
        <xs:sequence>
            <xs:element name="month">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="June"/>
                        <xs:enumeration value="August"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="year">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="2023"/>
                        <xs:enumeration value="2018"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="universityType">
        <xs:sequence>
            <xs:element type="xs:string" name="institution_name"/>
            <xs:element type="loc:degreeType" name="degree" xmlns:loc="http://localhost"/>
            <xs:element type="loc:engineering_graduation_averageType" name="engineering_graduation_average"
                        xmlns:loc="http://localhost"/>
            <xs:element type="loc:fromType" name="from" xmlns:loc="http://localhost"/>
            <xs:element type="loc:toType" name="to" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="educationType">
        <xs:sequence>
            <xs:element type="loc:universityType" name="university" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="companyType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="loc:addressType" name="address" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="role_descriptionType">
        <xs:sequence>
            <xs:element name="role">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration
                                value="Served at least 100 students and three teachers in one term (full-time)."/>
                        <xs:enumeration
                                value="Statistically analyzed each student’s progress in class and gave feedback and advice."/>
                        <xs:enumeration
                                value="Communicated among parents and teachers, solved students’ problems, supervised homework completion."/>
                        <xs:enumeration value="Maintained managed educational tools."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="experienceType">
        <xs:sequence>
            <xs:element type="xs:string" name="award"/>
            <xs:element type="xs:string" name="improvement"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="work_experienceType">
        <xs:sequence>
            <xs:element type="loc:companyType" name="company" xmlns:loc="http://localhost"/>
            <xs:element type="xs:string" name="position"/>
            <xs:element type="loc:role_descriptionType" name="role_description" maxOccurs="unbounded" minOccurs="0"
                        xmlns:loc="http://localhost"/>
            <xs:element type="loc:experienceType" name="experience" xmlns:loc="http://localhost"/>
            <xs:element type="loc:fromType" name="from" xmlns:loc="http://localhost"/>
            <xs:element type="loc:toType" name="to" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="resumeType">
        <xs:sequence>
            <xs:element type="loc:informationType" name="information" xmlns:loc="http://localhost"/>
            <xs:element type="loc:educationType" name="education" xmlns:loc="http://localhost"/>
            <xs:element type="loc:work_experienceType" name="work_experience" xmlns:loc="http://localhost"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jul-louis/Web-Development-Vol.1/part1/resume.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="resume.xsl"?>

<resume xmlns="http://localhost"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://localhost  resume.xsd">
    <information>
        <name>
            <firstname>Louis Jul.</firstname>
            <lastname>Kano</lastname>
        </name>
        <address>
            <street>100 Wellesley St E</street>
            <city>Toronto</city>
            <province>Ontario</province>
            <postal>M4Y 1H5</postal>
            <country>Canada</country>
        </address>
        <contact>
            <mobile>780-707-6801</mobile>
            <email>louis@krakenlouis.com</email>
        </contact>
    </information>

    <education>
        <university>
            <institution_name>University of Alberta</institution_name>
            <degree>
                <degree_type>Bachelor of Science</degree_type>
                <major>Computer Engineering (Software Option)</major>
                <faculty>Engineering</faculty>
                <department>Electrical and Computer Engineering</department>
                <career>Graduated with Distinction</career>
            </degree>
            <engineering_graduation_average>
                <grade_point_average>3.6</grade_point_average>
                <max_possible_value>4.0</max_possible_value>
                <status>Degree Granted</status>
            </engineering_graduation_average>
            <from>
                <month>September</month>
                <year>2018</year>
            </from>
            <to>
                <month>June</month>
                <year>2023</year>
            </to>
        </university>
    </education>

    <work_experience>
        <company>
            <name>Secondary School</name>
            <address>
                <city>City</city>
                <province>Province/State</province>
                <country>Country</country>
            </address>
        </company>

        <position>Teaching Assistant, Intern</position>
        <role_description>
            <role>Served at least 100 students and three teachers in one term (full-time).</role>
        </role_description>
        <role_description>
            <role>Statistically analyzed each student’s progress in class and gave feedback and advice.</role>
        </role_description>
        <role_description>
            <role>Communicated among parents and teachers, solved students’ problems, supervised homework completion.</role>
        </role_description>
        <role_description>
            <role>Maintained managed educational tools.</role>
        </role_description>

        <experience>
            <award>Awarded 1st place for work performance in teaching assistant group.</award>
            <improvement>Learned to communicate efficiently and professionally with clients and improved my time management skills.</improvement>
        </experience>
        <from>
            <month>June</month>
            <year>2018</year>
        </from>
        <to>
            <month>August</month>
            <year>2018</year>
        </to>
    </work_experience>

</resume>
